#![cfg(test)]

use soroban_sdk::{testutils::Address as _, Address, Env, Symbol};
use emergency_killswitch::{EmergencyKillswitch, Error};

// Client generated by soroban-sdk (standard for contract tests)
use emergency_killswitch::EmergencyKillswitchClient;

#[test]
fn test_unauthorized_emergency_trigger_regression() {
    let env = Env::default();
    env.mock_all_auths(); // Mock auth for test setup only

    let contract_id = env.register_contract(None, EmergencyKillswitch);
    let client = EmergencyKillswitchClient::new(&env, &contract_id);

    let admin = Address::generate(&env);
    let unauthorized = Address::generate(&env);
    let new_admin = Address::generate(&env);

    // 1. Initialize with admin (authorized path)
    client.initialize(&admin);

    // 2. Unauthorized caller cannot trigger emergency (pause = kill-switch activation)
    let res = client.try_pause();
    assert_eq!(res, Err(Error::Unauthorized));

    // 3. Unauthorized caller cannot unpause
    let res = client.try_unpause();
    assert_eq!(res, Err(Error::Unauthorized));

    // 4. Unauthorized caller cannot schedule unpause
    let future = env.ledger().timestamp() + 3600;
    let res = client.try_schedule_unpause(&future);
    assert_eq!(res, Err(Error::Unauthorized));

    // 5. Owner transfer regression + stale authority edge case
    // Admin transfers ownership
    client.transfer_admin(&new_admin); // succeeds because admin is authorized

    // OLD admin is now stale – must fail
    env.mock_auths(&[soroban_sdk::testutils::MockAuth::new(&admin, vec![&env])]);
    let res = client.try_pause();
    assert_eq!(res, Err(Error::Unauthorized));

    // NEW admin can trigger
    env.mock_auths(&[soroban_sdk::testutils::MockAuth::new(&new_admin, vec![&env])]);
    client.pause(); // must succeed

    // 6. ContractPaused error still respected after authorized trigger
    let res = client.try_unpause(); // still fails if not scheduled properly – but we test auth first
    // (full pause flow covered in other tests; this regression focuses on auth)

    // 7. is_paused remains readable by anyone (no auth required)
    assert!(client.is_paused());
}

#[test]
fn test_authorized_emergency_flow_coverage() {
    let env = Env::default();
    env.mock_all_auths();

    let contract_id = env.register_contract(None, EmergencyKillswitch);
    let client = EmergencyKillswitchClient::new(&env, &contract_id);

    let admin = Address::generate(&env);
    client.initialize(&admin);

    client.pause();
    assert!(client.is_paused());

    let future = env.ledger().timestamp() + 3600;
    client.schedule_unpause(&future);

    // Advance ledger to unpause time (Soroban test utils)
    env.ledger().set_timestamp(future);
    client.unpause();
    assert!(!client.is_paused());
}